import NextAuthProvider from '@/components/Providers/NextAuthProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToasterComponent from '@/lib/Toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>
          {children}
          <ToasterComponent />
        </NextAuthProvider>
      </body>
    </html>
  )
}
