export const softwareToolsNames = [
  'Zendesk',
  'Gorgias',
  'Shopify',
  'Front',
  'FreshDesk',
  'Other CRM tools',
  'Google Calendar',
  'Excel/Sheets',
  'Google Suite/Workspace',
  'Hubstaff',
  'Salesforce',
  'Hubspot',
  'Avaya',
  'AirCall',
  'Calendly',
  'ShipStation',
  'ShipHero',
  'Intercom',
  'Klayvio',
  'Attentive',
]
